on: [push, workflow_dispatch]

name: hoopR MBB Data trigger

jobs:
    hoopR_mbb_data_trigger:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger hoopR MBB Data
              uses: peter-evans/repository-dispatch@v2
              with:
                  token: ${{ secrets.SDV_GH_TOKEN }}
                  repository: sportsdataverse/hoopR-mbb-data
                  event-type: daily_mbb_data
                  client-payload: '{"ref": "refs/heads/main",
                                    "event_name": "daily_mbb_data"}'